embedding_size: 64
feat_embed_dim: 64
is_multimodal_model: False
n_layers: [1, 2, 3]
reg_weight: 1e-02
learning_rate: [1e-01]
dropout_rate: [0.1, 0.2, 0.3]
graph_dropout: True

cl_temperature: [0.3, 0.4, 0.5, 0.6, 0.7]
cl_weight: [0.1, 0.2, 0.3, 0.4, 0.5]

hyper_parameters: ["n_layers", "learning_rate", "dropout_rate", "cl_temperature", "cl_weight"]